### ISSUE TITLE
Private messages: Open a new Matrix room with a new message if Matrix user leaves the room

### ISSUE THREAD

**Issue by unclechu** [matrix-org/matrix-bifrost#217] opened 2020-12-02 04:45 UTC
**Describe the bug**
If you start a private chat with between two users in a MUC and Matrix user leaves the PM room XMPP bot does not leave the room (just my assumption) thus if you continue write something from XMPP side (you don’t see that the Matrix user left the room) the messages will be not delivered to the Matrix user anymore.

**To Reproduce**
1. Open a new PM chat between a Matrix user and XMPP conference user, does not matter on what side you start it (either Matrix or XMPP)
2. On the Matrix side leave that PM room
3. Continue write messages on XMPP side
4. See that any further messages will be no longer delivered

**Expected behavior**
When a Matrix user leaves a PM room the Bifröst bot notices it and also leaves this room. If XMPP user continue writing new messages a new PM Matrix room is created and Matrix user is invited there.

**Comment by jaller94** [comment] 2022-05-20 11:58
Closing as duplicate of https://github.com/matrix-org/matrix-bifrost/issues/213

**Closed by jaller94** 2022-05-20 11:58 UTC
Labels: duplicate, T-Defect
